name: Windows Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install CMake
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

    - name: Configure
      run: cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install

    - name: Build
      run: cmake --build _build --config Release

    - name: Install
      run: cmake --build _build --target install --config Release
